//
//  DefaultCommands.swift
//  AgentOrange
//
//  Created by Paul Leo on 10/01/2025.
//

struct DefaultCommands {
    static let all: [ChatCommand] = [
        ChatCommand(name: "correctness",
                    prompt: "Check the code carefully for correctness and security. Give helpful and constructive criticism for how to improve it.",
                    shortDescription: "Refactors the code",
                    role: "You are an expert reviewer of Swift 6 code.",
                    model: "qwen2.5-coder-32b-instruct",
                    host: "http://localhost:1234",
                    type: .reviewer),
        ChatCommand(name: "styleReview",
                    prompt: "Review the code for adherence to the language's style guide and best practices.",
                    shortDescription: "Reviews code style",
                    role: "You are a Swift 6 code style expert in this language.",
                    model: "qwen2.5-coder-32b-instruct",
                    host: "http://localhost:1234",
                    type: .reviewer),
        ChatCommand(name: "performance",
                    prompt: "Analyze the code for performance bottlenecks and provide optimization suggestions. Suggest ways to improve efficiency, focusing on time complexity, space complexity, and resource utilization. Provide a brief explanation for each suggestion. ",
                    shortDescription: "Optimizes performance",
                    role: "You are an expert in performance optimization for Swift 6.",
                    model: "qwen2.5-coder-32b-instruct",
                    host: "http://localhost:1234",
                    type: .reviewer),        
        ChatCommand(name: "comments",
                    prompt: "Add professional inline code comments while avoiding DocC documentation outside of functions.",
                    shortDescription: "Adds code comments",
                    role: "You are an expert professional Swift iOS engineer.",
                    type: .coder),
        ChatCommand(name: "docC",
                    prompt: "Add professional DocC documentation to the code.",
                    shortDescription: "Adds code documentation",
                    role: "You are an expert professional Swift iOS engineer.",
                    type: .coder),
        ChatCommand(name: "printlogs",
                    prompt: "Add or enhance logging in the code to make debugging and monitoring easier.",
                    shortDescription: "Improves logging",
                    role: "You are a monitoring and logging expert.",
                    type: .coder),
        ChatCommand(name: "refactor",
                    prompt: "Refactor the code to improve readability, maintainability, and performance (for Swift 6) while preserving its original functionality. Use descriptive names, break down large functions into smaller ones, maintain a logical order for easier reading, ensure each function follows the single responsibility principle, and limit variable scope",
                    shortDescription: "Refactors the code",
                    role: "You are an expert professional Swift iOS engineer specializing in clean code.",
                    type: .coder),
        ChatCommand(name: "solid",
                    prompt: "Please analyse the following code and apply the SOLID principles to enhance its design (for Swift 6). Make only necessary changes to improve the code’s structure and maintainability without over-complicating it while preserving its original functionality. Explain in code comments your changes and how they relate to specific SOLID principles. ",
                    shortDescription: "Analyses for SOLID principles",
                    role: "You are an expert professional Swift iOS engineer specializing in clean code.",
                    type: .coder),
        ChatCommand(name: "errorHandling",
                    prompt: "Please review the error handling in this code and suggest ways to make it clearer and more reliable. Consider exception handling, input validation, and how to handle failures gracefully. ",
                    shortDescription: "Improves error handling",
                    role: "You are an expert professional Swift iOS engineer specializing in clean code.",
                    type: .coder),
        ChatCommand(name: "mocks",
                    prompt: "Create mock-based objects for use within unit tests but don't create the unit tests.",
                    shortDescription: "Adds mock objects",
                    role: "You are an expert professional Swift iOS engineer in writing dependency-mock objects.",
                    model: "claude-3-5-sonnet-latest",
                    host: AGIServiceChoice.claude.name,
                    type: .coder),
        ChatCommand(name: "unittests",
                    prompt: "Create a suite of unit tests for this code using the new Swift Testing '#expect(...)' and @Test framework (NOT XCTest). For each test type, provide an example and explain its purpose. ",
                    shortDescription: "Adds unit tests",
                    role: "You are an expert professional Swift iOS engineer.",
                    model: "gpt-4o",
                    host: AGIServiceChoice.openai.name,
                    type: .coder),
        ChatCommand(name: "quickNimble",
                    prompt: "Create a suite of unit tests for this code using the Quick and Nimble framework and a describe(\"GIVEN...\") { context(\"WHEN...\") { it(\"THEN...\") }}} style. For each test type, provide an example and explain its purpose.",
                    shortDescription: "Adds unit tests",
                    role: "You are an expert professional Swift iOS engineer.",
                    model: "gemini-2.0-flash-exp",
                    host: AGIServiceChoice.gemini.name,
                    type: .coder),
        ChatCommand(name: "diff",
                    prompt: "Give me the diff markdown between the first original version of the code and the last version you provided.",
                    shortDescription: "Shows the diff",
                    role: "You are an expert professional Swift iOS engineer.",
                    model: "gemini-2.0-flash-exp",
                    host: AGIServiceChoice.gemini.name,
                    type: .coder),

    ]
}
